apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: monitoring
type: Opaque
data:
  DATA_SOURCE_NAME: cG9zdGdyZXM6ZXhhbXBsZXBhc3N3b3JkQG15LWRhdGFiYXNlLXBvc3RncmVzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyLz9zc2xtb2RlPWRpc2FibGU=
