apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    release: monitoring-stack # Change this based on your Prometheus deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-postgres-exporter
  endpoints:
    - port: http
      interval: 30s
  namespaceSelector:
    matchNames:
      - monitoring
