apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-config
  namespace: monitoring
data:
  postgres_exporter.yml: |
    databases:
      - name: "mydb"
        dsn: "postgres://postgres:examplepassword@my-database-postgresql.default.svc.cluster.local:5432/?sslmode=disable"
