apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/MattyDroidX/postgres-operator-deployments.git"
    targetRevision: HEAD
    path: database/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
